name: Deploy to ftp
  push:
    branches: [ "main" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: npm run export
    - uses: genietim/ftp-action@releases/v4
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "out"
        remoteDir: "Web"
